# Generated by Django 5.0.6 on 2024-06-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('In Progress', 'In Progress'), ('Deleted', 'Deleted'), ('Finished', 'Finished')], default='Active', max_length=255),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(blank=True, choices=[('To Do', 'Todo'), ('Doing', 'Doing'), ('Done', 'Done')], default='To Do', max_length=255),
        ),
    ]
