# Generated by Django 5.0.6 on 2024-06-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_projects_status_alter_tasks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='id_telegram',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
